-- Select Database
DROP DATABASE it191_course_project;
CREATE DATABASE it191_course_project;
USE it191_course_project;

-- Safe Update
SET SQL_SAFE_UPDATES = 0;

-- Clear Tables
DELETE FROM CollectionSong;
DELETE FROM Colllection;
DELETE FROM Song;

-- Drop Tables
DROP TABLE CollectionSong;
DROP TABLE Collection;
DROP TABLE Song;

SELECT * FROM CollectionSong;
SELECT * FROM Collection;
SELECT * FROM Song;


-- Create Tables

CREATE TABLE Song (
	song_id INT PRIMARY KEY auto_increment,
    artist VARCHAR(100),
    title VARCHAR(100),
    lyrics TEXT,
    duration INT,
    song_path VARCHAR(100),
    img_path VARCHAR(100)
);

CREATE TABLE Collection (
	collection_id INT PRIMARY KEY auto_increment,
    title VARCHAR(100) NOT NULL
);

CREATE TABLE CollectionSong (
	collection_id INT,
    song_id INT,
	PRIMARY KEY (collection_id, song_id),
    FOREIGN KEY (collection_id) REFERENCES Collection(collection_id) ON DELETE CASCADE,
    FOREIGN KEY (song_id) REFERENCES Song(song_id) ON DELETE CASCADE
);

SHOW TABLES;

INSERT INTO Collection VALUES (null, "Favorites");
INSERT INTO `song` (`song_id`, `artist`, `title`, `lyrics`, `duration`, `song_path`, `img_path`) VALUES
(null, 'Taylor Swift', 'invisible string', 'Green was the color of the grass\r\nWhere I used to read at Centennial Park\r\nI used to think I would meet somebody there\r\nTeal was the color of your shirt\r\nWhen you were sixteen at the yogurt shop\r\nYou used to work at to make a little money\r\nTime, curious time\r\nGave me no compasses, gave me no signs\r\nWere there clues I didn\'t see?\r\nAnd isn\'t it just so pretty to think\r\nAll along there was some\r\nInvisible string\r\nTying you to me?\r\nOoh\r\nBad was the blood of the song in the cab\r\nOn your first trip to LA\r\nYou ate at my favorite spot for dinner\r\nBold was the waitress on our three year trip\r\nGetting lunch down by the lakes\r\nShe said I looked like an American singer\r\nTime, mystical time\r\nCuttin\' me open, then healin\' me fine\r\nWere there clues I didn\'t see?\r\nAnd isn\'t it just so pretty to think\r\nAll along there was some\r\nInvisible string\r\nTying you to me?\r\nOoh\r\nA string that pulled me\r\nOut of all the wrong arms right into that dive bar\r\nSomething wrapped all of my past mistakes in barbed wire\r\nChains around my demons, wool to brave the seasons\r\nOne single thread of gold tied me to you\r\nCold was the steel of my axe to grind\r\nFor the boys who broke my heart\r\nNow I send their babies presents\r\nGold was the color of the leaves\r\nWhen I showed you around Centennial Park\r\nHell was the journey but it brought me heaven\r\nTime, wondrous time\r\nGave me the blues and then purple pink skies\r\nAnd it\'s cool, baby, with me\r\nAnd isn\'t it just so pretty to think\r\nAll along there was some\r\nInvisible string\r\nTying you to me?\r\nOoh\r\nHee\r\nOoh', 250, 'data/songs/Taylor Swift – invisible string.mp3', 'data/images/Invisible-String'),
(null, 'Mayonnaise', 'Synesthesia', 'Save your smile\r\nEverything fades through time\r\nI\'m lost for words\r\nEndlessly waiting for you\r\nStay with me\r\nYes, I know, this can\'t be\r\nAs morning comes\r\nI\'ll say goodbye to you when I\'m done\r\nThrough the sun\r\nBecause I\'m waiting for you\r\nWaiting for this dream to come true\r\nJust to be with you\r\nAnd if I die\r\nRemember these lines\r\nI\'m always here, guarding your life\r\nGuarding your life\r\nI am yours\r\nAnd I\'m completely trapped in your soul\r\nDazed and confused\r\nSwept away with your whole world\r\n\'Cause you\'re my star\r\nInvincible, haunting and far\r\nGrace under fire\r\nSomething is deep in my heart, in my heart\r\nBecause I\'m waiting for you\r\nWaiting for this dream to come true\r\nJust to be with you\r\nAnd if I die\r\nRemember these lines\r\nI\'m always here, guarding you\r\nSlowly falling into you\r\nI\'m obsessed with the fact that I\'m with you\r\nI can\'t breathe without you\r\nOoh, ooh, ooh, ooh, ooh-ooh\r\nI\'m waiting for you\r\nWaiting for this dream to come true\r\nJust to be with you\r\nAnd if I die\r\nRemember these lines\r\nI\'m always here, guarding your life\r\nOh, oh-oh, oh', 253, 'data/songs/Mayonnaise - Synesthesia.mp3', 'data/images/Synesthesia'),
(null, 'Aerosmith ', 'Dream On', 'Every time that I look in the mirror\r\nAll these lines on my face getting clearer\r\nThe past is gone\r\nOh, it went by like dusk to dawn\r\nIsn\'t that the way?\r\nEverybody\'s got their dues in life to pay, oh, oh, oh\r\nI know nobody knows\r\nWhere it comes and where it goes\r\nI know it\'s everybody\'s sin\r\nYou got to lose to know how to win\r\nHalf my life\'s in books\' written pages\r\nStoring facts learned from fools and from sages\r\nYou view the earth\r\nOh, sing with me, this mournful dub\r\nSing with me, sing for a year\r\nSing for the laughter, and sing for the tear\r\nSing with me, if it\'s just for today\r\nMaybe tomorrow, the good Lord will take you away\r\nOh, sing with me, sing for the year\r\nSing for the laughter, and sing for the tear\r\nSing it with me, if it\'s just for today\r\nMaybe tomorrow, the good Lord will take you away\r\nDream on\r\nDream on\r\nI dream on\r\nDream a little, I\'ll dream on\r\nDream on\r\nI dream on\r\nI dream on\r\nDream a little, I\'ll dream on\r\nDream on\r\nDream on\r\nDream on\r\nI\'ll dream on\r\nDream on\r\nDream on\r\nI dream on', 268, 'data/songs/Aerosmith - Dream On.mp3', 'data/images/Dream-on'),
(null, 'Lola Amour', 'Fallen', 'What if I told you that I\'ve fallen\r\nAnd I like the way you say my name?\r\nMy heart skips a beat when I hear you calling\r\nAnd I like that it won\'t go away\r\nBut never mind, don\'t wanna give you any trouble\r\nNever mind, never mind\r\nI\'m OK with being by your side for as long as I can hide\r\nWhat if I told you that I\'ve fallen?\r\nWhat if I told you that I\'ve fallen?\r\nThe heart-shaped arrow through my chest\r\nI\'ll make your breakfast every morning\r\nAnd pick you up when you\'re a mess\r\nBut I know that it won\'t ever stop\r\nYou know I\'ll be there when you call me whether you like it or not\r\nWithout a warning, now I\'m falling for this picture on my phone\r\nBut don\'t mind me, I\'m just falling, I\'ll be back up on my own\r\nPlease don\'t say my name, help me put out this flame\r\nI\'d rather hold onto this feeling that you don\'t even believe in\r\nWhat if I told you that I\'ve fallen?\r\nWhat if I told you that I\'ve fallen?\r\nNevermind, nevermind, nevermind\r\nWhat if I told you that I\'ve fallen?\r\nNevermind, nevermind, nevermind\r\nWhat if I told you that I\'ve fallen?\r\nNevermind, nevermind, nevermind\r\nWhat if I told you that I\'ve fallen?\r\nNevermind, nevermind, nevermind\r\nWhat if I told you that I\'ve fallen? (Nevermind)\r\nWhat if I told you that I\'ve fallen? (Oh, nevermind)\r\nWhat if I told you that I\'ve fallen? (Oh, nevermind)\r\nWhat if I told you that I\'ve fallen? (Oh, nevermind, I said nevermind)\r\nI shouldn\'t tell you that I\'ve fallen', 201, 'data/songs/Lola Amour - Fallen.mp3', 'data/images/Fallen'),
(null, 'Silent Sanctuary', 'Bumalik Ka Na Sa\'kin', '… Magaan na ba ang \'yong paghinga bumalik ka na sa\'kin\r\nKlaro na ba ang isip sinta bumalik ka na sa\'kin\r\nHindi ka na nagparamdam\r\nBuhat ng cool off ako\'y nahibang\r\n… Sige na please \'wag nang mainis bumalik ka na sa\'kin\r\nSorry mahal ika\'y nasaktan bumalik ka na sa\'kin\r\nBumalik ka na sa akin\r\n… Kung pababayaan lang kita baka tuluyan ka nang mawala\r\nSana naman pagbigyan mo na pangakong \'di na mauulit pa\r\nKatulad mong tao lang ako\r\nNapapasabak din sa gulo\r\n… Sige na please \'wag nang mainis bumalik ka na sa\'kin\r\nSorry mahal ika\'y nasaktan bumalik ka na sa\'kin\r\n… \'Wag mo sana akong ipagpalit (akong ipagpalit)\r\nIkaw at ako na lang ulit\r\nUlit\r\n… Sige na please \'wag nang mainis bumalik ka na sa\'kin\r\nSorry mahal ika\'y nasaktan bumalik ka na sa\'kin\r\nSige na please \'wag nang mainis bumalik ka na sa\'kin\r\nSorry mahal ika\'y nasaktan bumalik ka na sa\'kin\r\n… Sige na please (bumalik ka na sa\'kin)\r\nSorry mahal (bumalik ka na sa\'kin)\r\nBumalik ka na sa akin', 215, 'data/songs/Silent Sanctuary - Bumalik Ka Na Sa\'kin.mp3', 'data/images/Bumalik-kana-sakin'),
(null, 'Adie', 'Paraluman', 'Sa unang tingin, agad na nahumaling\r\nSa nagniningning mong mga mata\r\nIka\'y isang bituin na nagmula sa langit\r\nHindi ko mawari ang taglay mong tinatangi\r\nSadya namang nakakabighani\r\n\'Di maipaliwanag ang nararamdaman (ooh)\r\nNamumukadkad ang aking ligaya\r\nSa tuwing ika\'y papalapit na\r\nHawakan mo ang aking kamay\r\nOh, Paraluman\r\nIka\'y akin nang dadalhin sa\r\n\'Di mo inaasahang paraiso (hoo-hoo)\r\nPalagi kitang aawitan ng Kundiman\r\n\'Di magsasawa, \'di ka pababayaan\r\nIsasayaw kita hanggang sa walang hanggan (hoo-hoo, hoo-hoo)\r\nMga gunita na laging naiisip (naiisip)\r\nSumisilip (sumisilip) ang itinakda ng mahiwaga\r\nLiwanag na dulot mo, nagbigay sinag sa madilim kong mundo (ooh-ooh-oh)\r\nIbang-iba ako kapag ikaw na ang kapiling\r\nSumisiping ang buwan at mga bituin\r\nNa para bang sumasang-ayon sa atin ang kalawakan (kalawakan)\r\nNamumukadkad ang aking ligaya\r\nSa tuwing ika\'y papalapit na\r\nHawakan mo ang aking kamay (hoo-hoo)\r\nOh, Paraluman\r\nIka\'y akin nang dadalhin sa\r\n\'Di mo inaasahang paraiso (paraiso, hoo-hoo)\r\nPalagi kitang aawitan ng Kundiman\r\n\'Di magsasawa, \'di ka pababayaan\r\nIsasayaw kita hanggang sa walang hanggan (hoo-hoo, hoo-hoo)\r\nPara-pa-pa-para-Paraluman (hoo-hoo, hoo-hoo)\r\nPara-pa-pa-para-Paraluman (hoo-hoo, hoo-hoo)\r\nPara-pa-pa-para-Paraluman (hoo-hoo, hoo-hoo)\r\nPara-pa-pa-para-Paraluman (hoo-hoo, hoo-hoo)\r\nPara-pa-pa-para-Paraluman (hoo-hoo, hoo-hoo)\r\nPara-pa-pa-para-Paraluman (hoo-hoo, hoo-hoo)\r\nPara-pa-pa-para-Paraluman (hoo-hoo, hoo-hoo)\r\nHimig ng tadhana (ah, ah)\r\nSa atin ay tumutugma na (tumutugma na)\r\nHimig ng tadhana (ah, ah)\r\nSa atin ay tumutugma na (tumutugma na)\r\nHimig ng tadhana (ah, ah)\r\nSa atin ay tumutugma na (ooh-ooh-ooh, hoo-hoo, hoo)\r\nOh, Paraluman\r\nIka\'y akin nang dadalhin sa\r\n\'Di mo inaasahang paraiso\r\nPalagi kitang aawitan ng Kundiman\r\n\'Di magsasawa, \'di ka pababayaan\r\nIsasayaw kita, mamahalin kita\r\nHanggang sa walang hanggan (hoo-hoo, hoo-hoo)', 445, 'data/songs/Adie - Paraluman.mp3', 'data/images/Paraluman'),
(null, 'New Jeans', 'Super shy', '[Chorus: Danielle, Hyein, Hanni, Haerin]\r\nI\'m super shy, super shy\r\nBut wait a minute while I make you mine, make you mine\r\nTteollineun jigeumdo, you\'re on my mind all the time\r\nI wanna tell you but, I\'m super shy, super shy\r\nI\'m super shy, super shy\r\nBut wait a minute while I make you mine, make you mine\r\nTteollineun jigeumdo, you\'re on my mind all the time\r\nI wanna tell you but, I\'m super shy, super shy\r\n\r\n[Verse 1: Hyein, Minji]\r\nAnd I wanna go out with you\r\nWhere you wanna go? (Huh?)\r\nFind a lil spot, just sit and talk\r\nLooking pretty, follow me\r\nUri duri naranhi\r\nBoiji? (bwa)\r\nNae nuni (Heh)\r\nGapjagi, binnaji\r\nWhen you say I\'m your dream\r\n\r\n[Refrain: Hanni, Danielle, Minji]\r\nYou don\'t even know my name, do ya?\r\nYou don\'t even know my name, do ya?\r\nNugubodado\r\n[Chorus: Haerin, Hyein, Hanni, Danielle]\r\nI\'m super shy, super shy\r\nBut wait a minute while I make you mine, make you mine\r\nTteollineun jigeumdo, you\'re on my mind all the time\r\nI wanna tell you but, I\'m super shy, super shy\r\nI\'m super shy, super shy\r\nBut wait a minute while I make you mine, make you mine\r\nTteollineun jigeumdo, you\'re on my mind all the time\r\nI wanna tell you but, I\'m super shy, super shy\r\n\r\n[Verse 2: Minji, Hanni]\r\nNa wollae maldo jalhago geureonde wae ireonji\r\nI don\'t like that\r\nSomething odd about you\r\nYeah, you\'re special and you know it\r\nYou\'re the top, babe\r\n\r\n[Chorus: Danielle, Haerin, Hyein, Minji]\r\nI\'m super shy, super shy\r\nBut wait a minute while I make you mine, make you mine\r\nTteollineun jigeumdo, you\'re on my mind all the time\r\nI wanna tell you but, I\'m super shy, super shy\r\nI\'m super shy, super shy\r\nBut wait a minute while I make you mine, make you mine\r\nTteollineun jigeumdo, you\'re on my mind all the time\r\nI wanna tell you but, I\'m super shy, super shy', 200, 'data/songs/NewJeans - Super Shy.mp3', 'data/images/Super_shy'),
(null, 'Stephen Sanchez', 'Until I Found You', 'Georgia, wrap me up in all your\r\nI want you in my arms\r\nOh, let me hold you\r\nI\'ll never let you go again like I did\r\nOh, I used to say\r\nI would never fall in love again until I found her\r\nI said, \"I would never fall unless it\'s you I fall into\"\r\nI was lost within the darkness, but then I found her\r\nI found you\r\nGeorgia, pulled me in, I asked to\r\nLove her once again\r\nYou fell, I caught you\r\nI\'ll never let you go again like I did\r\nOh, I used to say\r\nI would never fall in love again until I found her\r\nI said, \"I would never fall unless it\'s you I fall into\"\r\nI was lost within the darkness, but then I found her\r\nI found you\r\nI would never fall in love again until I found her\r\nI said, \"I would never fall unless it\'s you I fall into\"\r\nI was lost within the darkness, but then I found her\r\nI found you', 174, 'data/songs/Stephen Sanchez - Until I Found You.mp3', 'data/images/Until-I-Found-You'),
(null, 'Taylor Swift', 'Enchanted', 'There I was again tonight\r\nForcing laughter, faking smiles\r\nSame old tired, lonely place\r\nWalls of insincerity, shifting eyes and vacancy\r\nVanished when I saw your face\r\nAll I can say is, it was enchanting to meet you\r\nYour eyes whispered, \"Have we met?\"\r\n\'Cross the room your silhouette\r\nStarts to make its way to me\r\nThe playful conversation starts\r\nCounter all your quick remarks\r\nLike passing notes in secrecy\r\nAnd it was enchanting to meet you\r\nAll I can say is, I was enchanted to meet you\r\nThis night is sparkling, don\'t you let it go\r\nI\'m wonderstruck, blushing all the way home\r\nI\'ll spend forever wondering if you knew\r\nI was enchanted to meet you\r\nThe lingering question kept me up\r\n2 AM, who do you love?\r\nI wonder \'til I\'m wide awake\r\nAnd now I\'m pacing back and forth\r\nWishing you were at my door\r\nI\'d open up and you would say, \"Hey\"\r\nIt was enchanting to meet you\r\nAll I know is, I was enchanted to meet you\r\nThis night is sparkling, don\'t you let it go\r\nI\'m wonderstruck, blushing all the way home\r\nI\'ll spend forever wondering if you knew\r\nThat this night is flawless, don\'t you let it go\r\nI\'m wonderstruck, dancing around all alone\r\nI\'ll spend forever wondering if you knew\r\nI was enchanted to meet you\r\nThis is me praying that\r\nThis was the very first page\r\nNot where the story line ends\r\nMy thoughts will echo your name, until I see you again\r\nThese are the words I held back, as I was leaving too soon\r\nI was enchanted to meet you\r\nPlease don\'t be in love with someone else\r\nPlease don\'t have somebody waiting on you\r\nPlease don\'t be in love with someone else\r\nPlease don\'t have somebody waiting on you\r\nThis night is sparkling, don\'t you let it go\r\nI\'m wonderstruck, blushing all the way home\r\nI\'ll spend forever wondering if you knew\r\nThis night is flawless, don\'t you let it go\r\nI\'m wonderstruck, dancing around all alone\r\nI\'ll spend forever wondering if you knew\r\nI was enchanted to meet you\r\nPlease don\'t be in love with someone else\r\nPlease don\'t have somebody waiting on you', 356, 'data/songs/Taylor Swift - Enchanted.mp3', 'data/images/Enchanted'),
(null, 'YOASOBI', 'Racing Into The Night', '沈むように溶けてゆくように\r\n二人だけの空が広がる夜に\r\n「さよなら」だけだった\r\nその一言で全てが分かった\r\n日が沈み出した空と君の姿\r\nフェンス越しに重なっていた\r\n初めて会った日から\r\n僕の心の全てを奪った\r\nどこか儚い空気を纏う君は\r\n寂しい目をしてたんだ\r\nいつだってチックタックと\r\n鳴る世界で何度だってさ\r\n触れる心無い言葉うるさい声に\r\n涙が零れそうでも\r\nありきたりな喜びきっと二人なら見つけられる\r\n騒がしい日々に笑えない君に\r\n思い付く限り眩しい明日を\r\n明けない夜に落ちてゆく前に\r\n僕の手を掴んでほら\r\n忘れてしまいたくて閉じ込めた日々も\r\n抱きしめた温もりで溶かすから\r\n怖くないよいつか日が昇るまで\r\n二人でいよう\r\n君にしか見えない\r\n何かを見つめる君が嫌いだ\r\n見惚れているかのような恋するような\r\nそんな顔が嫌いだ\r\n信じていたいけど信じれないこと\r\nそんなのどうしたってきっと\r\nこれからだって いくつもあって\r\nそのたんび怒って 泣いていくの\r\nそれでもきっといつかはきっと 僕らはきっと\r\n分かり合えるさ 信じてるよ\r\nもう嫌だって疲れたんだって\r\nがむしゃらに差し伸べた 僕の手を振り払う君\r\nもう嫌だって 疲れたよなんて\r\n本当は僕も言いたいんだ\r\nAh ほらまたチックタックと\r\n鳴る世界で何度だってさ\r\n君の為に用意した言葉 どれも届かない\r\n「終わりにしたい」 だなんてさ\r\n釣られて言葉にした時\r\n君は初めて笑った\r\n騒がしい日々に笑えなくなっていた\r\n僕の目に映る君は綺麗だ\r\n明けない夜に零れた涙も\r\n君の笑顔に溶けていく\r\n変わらない日々に泣いていた僕を\r\n君は優しく終わりへと誘う\r\n沈むように溶けてゆくように\r\n染み付いた霧が晴れる\r\n忘れてしまいたくて閉じ込めた日々に\r\n差し伸べてくれた君の手を取る\r\n涼しい風が空を泳ぐように今 吹き抜けていく\r\n繋いだ手を離さないでよ\r\n二人いま 夜に駆け出していく', 261, 'data/songs/YOASOBI - Racing Into The Night.mp3', 'data/images/Racing-into-the-night');

SELECT * FROM Song;
SELECT * FROM Collection;
SELECT * FROM CollectionSong;


SELECT s.*, CASE WHEN cs.song_id IS NOT NULL THEN 'true' ELSE 'false' END AS in_favorites
FROM Song s
LEFT JOIN CollectionSong cs
ON s.song_id = cs.song_id
LEFT JOIN Collection c
ON cs.collection_id = c.collection_id AND c.title = 'Favorites';



SELECT s.*, CASE WHEN cs.song_id IS NOT NULL THEN 'true' ELSE 'false' END AS in_favorites
FROM Song s
LEFT JOIN CollectionSong cs
ON s.song_id = cs.song_id
LEFT JOIN Collection c
ON cs.collection_id = c.collection_id AND c.title = 'Favorites'
WHERE cs.collection_id = 1;